FROM node:18.16.0-slim AS build

WORKDIR /app

COPY frontend frontend

WORKDIR /app/frontend

RUN npm install

RUN npm run build

FROM node:18.16.0-slim AS production

ENV NODE_ENV=production
ENV PORT=8000

WORKDIR /app

COPY backend backend

COPY --from=build /app/frontend/build ./frontend/build

WORKDIR /app/backend

RUN npm install

CMD ["npm", "run", "start"]